CREATE DATABASE IF NOT EXISTS mycloud CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE mycloud;

CREATE TABLE IF NOT EXISTS usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  pass_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);